### ISSUE TITLE
Progress bar going backwards

### ISSUE THREAD

**Issue by Bluenix2** [CitiesSkylinesMultiplayer/CSM#218] opened 2020-12-20 18:34 UTC
**Summary**
When my client is connecting, the bar first quickly goes through it all. Then it starts going backwards to 1/3, then continues as usual. Perhaps it would be good to have some consistency and not have this behavior.

This was experienced yesterday, and when connecting today again (on the newest release) we experienced this again.

**To Reproduce**
1. Create and host a game
2. Have someone connect, perhaps with a slower computer
3. Take note of the progress bar
4. See funky loading bar

*I can probably attach a video of this in Discord, forgot to record*

**Comment by kaenganxt** [comment] 2020-12-22 22:34
Closing this issue since we don't have a loading bar yet for our part :) (see #177) and it seems this is completely caused by Cities itself.

**Closed as completed by kaenganxt** 2020-12-22 22:34 UTC
Labels: bug
