### ISSUE TITLE
Building Bus stops lets roads dissapear

### ISSUE THREAD

**Issue by Myrdok** [CitiesSkylinesMultiplayer/CSM#103] opened 2019-04-17 20:39 UTC
**Describe the bug**
If you build bus stops for a bus route, after the first bus stop, every thing goes crazy. Even if you just want to place the next bus stop one street further, it will make randome routes. You will recognize, that roads just dissappear or getting kinda blue or green.

**To Reproduce**
1. Build Bus Depot
2. Start Building Bus Stops
3. Place First Bus Stop
4. Try to place Second or Third Bus Stop just along the street

**Expected behavior**
You can build bus stops and have a working route just straight the street

**Screenshots**
I did not take some, but I will hopefully tomorrow and attach, sorry.

**Additional context**
Works fine after disconnecting.

Thank you!

**Comment by bartaferi** [comment] 2019-05-04 14:38
Same problem with train routes.

**Comment by kaenganxt** [comment] 2019-05-12 19:07
Public transport lines are not yet implemented.
I'll close this as a duplicate of #71

**Closed as completed by kaenganxt** 2019-05-12 19:07 UTC
Labels: duplicate
