### ISSUE TITLE
Road & Water Pipe - Bug

### ISSUE THREAD

**Issue by Areeth** [CitiesSkylinesMultiplayer/CSM#47] opened 2018-11-05 18:08 UTC
Hi!
That's It when I create roads (one way roads)
![road2](https://user-images.githubusercontent.com/44783341/48016782-cda8c300-e12c-11e8-9daf-8ee11222d7f2.png)
![road3](https://user-images.githubusercontent.com/44783341/48016781-cda8c300-e12c-11e8-9e5e-9cfd8ae2df03.png)
![road4](https://user-images.githubusercontent.com/44783341/48016784-cda8c300-e12c-11e8-8c07-6a18a8c81109.png)

**Comment by Treholt3103** [comment] 2018-11-05 19:56
Hey Arreth i can't seem to recreate the problem, can you try to describe how the problem was generated in steps :) Also are you playing over LAN or over the internet?

**Comment by Areeth** [comment] 2018-11-06 13:17
Hi!
We playing with Hamachi.
I'm build a road, and the road is not visible for my friend (Picture 1: Vision of me and my friend)
We can't connect pipe to water pump station (Picture 2 & 3)

**Comment by Treholt3103** [comment] 2018-11-06 13:47
When i reviewed the code yesterday i found a bug, that might help solve this, but one other question, are any of you using Left-hand Traffic?

**Comment by Areeth** [comment] 2018-11-06 13:53
I don't use left-hand traffic

**Comment by Areeth** [comment] 2018-11-07 14:16
Roads bugging for my friend
![road5](https://user-images.githubusercontent.com/44783341/48136409-e2f22e80-e29f-11e8-89b2-ba3f2cd1e185.png)

**Comment by Treholt3103** [comment] 2018-11-07 14:43
Are both of you updated to the newest Github (not steam) version?
And some questions to the picture, is the problem only the wierd looking roundabout, or are some of the roads seen in the background not comming over?

**Comment by Treholt3103** [comment] 2018-11-07 15:34
And is the problem with creating or deleting roads, or both? (i'm unsure of how many bugs the picture contains)?

**Comment by Areeth** [comment] 2018-11-07 15:55
I create a road, It's good for me. But when lot a road in the map, my friend roads is get bugged (picture)
I was deleted the roads, and I rebuild them, but not worked.

(Sorry for my English. I'm studying the language. 😄 )

**Comment by Treholt3103** [comment] 2018-11-07 16:03
Okay, i just committed a small bugfix changing the way Roads are created, and it might solve the problem, so when the mod is updated please try again and se if it solves the problem :)

**Comment by ZeNico13** [comment] 2018-11-09 20:53
Hello !
We have the same problem with my friend.

**Here is the Server view :**
![doubles tuyaux d eau vue serveur](https://user-images.githubusercontent.com/44881945/48286890-57c39500-e467-11e8-9455-3506081cf485.png)

**Here is the Client view :**
![doubles tuyaux d eau vue client](https://user-images.githubusercontent.com/44881945/48286925-775abd80-e467-11e8-8140-ce32364913d0.png)

You can see that there are two pipes on the client side.
In fact, the Client built a water pipe but I did not see it. So, I also built a pipe on my side (Server).

In addition, another problem: we are unable to connect water pipes between them and water pipes to water towers / pumping stations.

**Comment by Treholt3103** [comment] 2018-11-09 22:53
Yes, im looking at it right now and i believe there are at least three different bugs creating these problems,
The problem with the watertower are caused by a double node being created, the missing connections are caused by some bug in how its handling connecting nodes and node segments, and a last bug is caused by the vector dictionary and the lack of ability to differentiate things in the ground and roads.

**Comment by DominicMaas** [comment] 2018-12-09 02:02
This issue was auto closed, still need to check if https://github.com/DominicMaas/Tango/pull/64 has fixed this bug.

**Closed as completed** 2018-12-15 21:19 UTC
