### ISSUE TITLE
Placing Recycling Centre creates wrong building on host

### ISSUE THREAD

**Issue by James-Archer** [CitiesSkylinesMultiplayer/CSM#113] opened 2019-06-04 07:02 UTC
Hosting the game with a single other connection. The other player placed a _Recycling Centre_, which operated properly in their game. Host-side I saw a _Solar Updraft Tower_, which operated accordingly.

The hitbox of the building is correct for the _Recycling Centre_ in both games. 

Screenshots of both situations:
![Screenshot](https://user-images.githubusercontent.com/8492496/58857906-a8435e00-86e9-11e9-994f-2ac0cc6ba208.png)

![Screenshot 2](https://user-images.githubusercontent.com/8492496/58857913-abd6e500-86e9-11e9-881a-a657c63cf754.png)

**Comment by kaenganxt** [comment] 2019-06-04 08:33
Did anyone of you have some mods or DLCs installed? If yes, could you please try it again without them?

**Comment by fred-cardoso** [comment] 2019-11-10 16:18
I am testing with the latest version of the mod and placing recycle center via client works as expected and shows the same building on host. I hope it can help you guys debug the situation.

**Comment by kaenganxt** [comment] 2019-12-08 16:43
Closing this as it seems to be fixed or caused by having different DLCs.

**Closed as completed by kaenganxt** 2019-12-08 16:43 UTC
Labels: bug, sync-issue
