### ISSUE TITLE
Timed out join

### ISSUE THREAD

**Issue by Bluenix2** [CitiesSkylinesMultiplayer/CSM#219] opened 2020-12-20 18:53 UTC
### Summary
My client, who has a rather slow computer and connection, timed out when connecting. But he continued to load...

In the end he was disconnected, and didn't sync with me and couldn't be found on the players list. But he was playing on the world, because that had loaded.

If it is to any help, it usually takes quite long to start the game and load the world. Very long.
But the game doesn't freeze, just takes quite some time to load.

### To Reproduce
1. Start a game and host.
2. Have someone with perhaps not the best PC configuration join.
3. See "... is joining..." and chat.
4. Then see in chat how client timed out, but from their point of view game just continued to load.
5. Client loads into the world, but no synchronization is done and they are completely disconnected from the host.

**Comment by kaenganxt** [comment] 2020-12-22 22:38
Closing as duplicate of #212

**Closed as completed by kaenganxt** 2020-12-22 22:38 UTC
Labels: bug
