### ISSUE TITLE
When i start a game with multiplayer mod activated i getting a error

### ISSUE THREAD

**Issue by RickardPettersson** [CitiesSkylinesMultiplayer/CSM#111] opened 2019-05-21 19:49 UTC
I subscribed to the mod in workshop and then activated in content manager in the game and then started a new game and first thing i getting is "AN ERROR OCCURRED" and error message showed:

The Mod D:\Spel\SteamLibrary\steamapps\workshop\content\255710\1558438291 [0Harmony.dll, NLog.dll, LiteNetLib.dll, System.Threading.dll, Open.Nat.dll, protobuf-net.dll, CSM.dll] has caused an error [ModException]

Details:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
  at System.Array.CopyTo (System.Array array, Int32 index) [0x00000] in <filename unknown>:0 
  at CSM.Extensions.EconomyExtension.OnCreated (IEconomy economy) [0x00000] in <filename unknown>:0 
  at EconomyWrapper.OnEconomyExtensionsCreated () [0x00000] in <filename unknown>:0

**Comment by kaenganxt** [comment] 2019-05-21 20:56
This issue was caused by today's Cities Skylines update and has already been fixed on the master branch in 33f3bcf9aa6468b898aebccb621198097dcc3d33. Please use the development version for now as described in the [Readme](https://github.com/DominicMaas/Tango#download--install).

**Closed as completed by kaenganxt** 2019-05-21 20:56 UTC
