### ISSUE TITLE
Desynchronisation on Zoning

### ISSUE THREAD

**Issue by JakeAllswo** [CitiesSkylinesMultiplayer/CSM#158] opened 2019-12-24 21:53 UTC
The bug is where the host or other players set a specific zone and then the other player(s) desynchronise from the placement of the zonal area give e.g. 
If Player 1 sets an area as a residential area the other player(s) would desynchronise, but not entirely. You can still see constructions being made in sync with the rest of the game. The only problem I have is the desynchronisation when the area zoning is set. 
Usually its fine with two people as soon as the third joins there seems to be quite a heavy desync issue. Or if the third person joins mid way through a game. Two on two seems to be completely fine but having a third seems to have a few more desynchronise errors.

1. Go to the game with one or two friends.
2. Click on Zoning.
3. Click a any zone of your choice, and talk to your friend and see if there is any difference in zonal areas.
4. Error could usually be picked on on the host sharing their screen.

May not happen for everyone or every try you do it.
But for us it has. 

Many Thanks 
Jake

**Comment by markusa380** [comment] 2020-02-26 21:50
Experiencing the same issue.

**Comment by measosphere** [comment] 2020-03-01 00:15
I'm having the same issue as well.

**Comment by codemonkee** [comment] 2020-04-03 04:34
I'm trying the mod for the first time (2003.3.0); two computes on the same network initial tests are pretty good. This is the first sync issue I noticed, but behalves a little different from what is described.

In my case I only have 2 users. As soon as one of the players zones an area the syncing will stop but not completely as some oddities
- One system will develop the buildings in the zoned area
- Placing roads becomes a one-way sync
- Pause/Play is still syncing fine

running the /sync command everything seems to behave until one of the plays zones again.
happy to collect any information that would be beneficial or test things out.

**Comment by kaenganxt** [comment] 2020-04-10 22:52
Duplicate of #172 (Also thanks for the additional information!)

**Closed as completed by kaenganxt** 2020-04-10 22:52 UTC
Labels: duplicate
