### ISSUE TITLE
Waterpipes/Powerlines sync uncorrectly when placed on top of each other; Powerlines not rotating

### ISSUE THREAD

**Issue by MisterX2000** [CitiesSkylinesMultiplayer/CSM#42] opened 2018-11-03 11:55 UTC
When you place a powerline and underneath the power pylon a water pipe the power pylon disappears.
Here's a short video, to visualize the problem:
https://streamable.com/b43cp

**Comment by Treholt3103** [comment] 2018-11-03 16:03
Thanks for the video :) i belive that there is something wrong with how the building script handle releases (deletion), in my earlyer testes i have seen a waterpipe remove a Power plant. I will take a look at it :)

**Comment by Treholt3103** [comment] 2018-11-04 21:43
This problem should  be fixed now with the newest update :)

**Comment by MisterX2000** [comment] 2018-11-05 18:42
It's fixed, but I discovered another bug.
The rotation of the power pylon isn't synced correctly to the client.
![powerpylon](https://user-images.githubusercontent.com/1662351/48019049-c684b380-e132-11e8-94c7-f62d016579be.png)

**Comment by Treholt3103** [comment] 2018-11-05 20:02
I see, the problem is that when you are extending the powerline, the building that you are extending from are not updating, so that buildings new angle is not send to the Client :) fixing it would require that we are somehow able to identify the original created powerline and send it's new angle over.
It should be possible, but i don't think it will be an immediate priority, since its not a gamebreaking problem :)

**Closed as completed** 2018-12-31 02:09 UTC
Labels: bug
