### ISSUE TITLE
Index out of range when creating new metro line.

### ISSUE THREAD

**Issue by TheCadde** [CitiesSkylinesMultiplayer/CSM#163] opened 2020-01-11 09:34 UTC
Keep getting random index out of range after creating new metro lines.
Nog log currently because we are too "busy" playing and i didn't copy the log/stacktrace.

Steam workshop version Dec 23, no DLC active, no other mods running.

Just a heads up really. Can attach log next time it happens.

**Comment by kaenganxt** [comment] 2020-02-03 21:51
Closing this as I can't reproduce your issue. If you have the problem again, feel free to reopen this issue and attach a log file or some steps to reproduce.

**Closed as completed by kaenganxt** 2020-02-03 21:51 UTC

**Comment by xaqq** [comment] 2020-06-11 23:00
Hello, believe I ecountered the same issue.
I was hosting server and client was building metro line.

Here is log file: [log-current.txt](https://github.com/CitiesSkylinesMultiplayer/CSM/files/4767710/log-current.txt)

Also see #173

**Comment by kaenganxt** [comment] 2020-06-12 00:31
@xaqq Thanks for the additional info. Could you please also provide the log file from the day before? Log files are split at midnight and issue seems to have started just before midnight :)

**Comment by xaqq** [comment] 2020-06-14 15:04
@kaenganxt No problem.

Unfortunately the previous log file contain no relevant information.
[log-2020-06-12.txt](https://github.com/CitiesSkylinesMultiplayer/CSM/files/4776672/log-2020-06-12.txt)
